# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_bar', models.CharField(max_length=150)),
                ('top_text', models.CharField(max_length=150)),
                ('color_background', models.CharField(max_length=150)),
                ('color_text', models.CharField(max_length=150)),
                ('logo', models.CharField(max_length=200)),
                ('icono', models.CharField(max_length=200)),
                ('social', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
