# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='color_background',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='template',
            name='color_text',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='template',
            name='icono',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template',
            name='logo',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template',
            name='social',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_bar',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_text',
            field=models.TextField(max_length=150),
        ),
    ]
