# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171223_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='icono',
            field=models.ImageField(upload_to='images/template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='logo',
            field=models.ImageField(upload_to='images/template'),
        ),
    ]
