# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171223_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='color_background',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='color_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='social',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_bar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='top_text',
            field=models.TextField(),
        ),
    ]
